### ISSUE TITLE
Add references to lt_line script

### ISSUE THREAD

**Issue by profxj** [linetools/linetools#430] opened 2017-11-16 17:47 UTC
as titled.

**Comment by profxj** [comment] 2017-11-16 17:49
Figure out SiIV f-value too

**Comment by profxj** [comment] 2017-11-16 17:50
And CIV 1550

**Comment by profxj** [comment] 2017-11-16 17:52
Likely to be bad book-keeping in llist_v1.2.ascii

**Comment by ntejos** [comment] 2017-11-18 23:43
Just to catch up, what happened here? Did we have wrong values for w0 and fosc for these transitions?

**Comment by profxj** [comment] 2017-11-19 00:00
Yes, the wrong ones were being pulled because
of the rest wavelength values in the set file.

**Comment by ntejos** [comment] 2017-11-19 00:03
I see, thanks. But now, how do we know this error is contained to these transitions only? Shouldn't we create the set file again from scratch?

**Comment by profxj** [comment] 2017-11-19 00:18
You are encouraged to query what fraction of the lines
are *not* in Morton 2003.  It is a good point.
  
@yzhenggit and I did check the lines that she
is working on.

**Comment by yzhenggit** [comment] 2017-11-19 03:27
To keep everyone updated: @profxj  and I have double checked these lines: PII 1152, PII1301, FeII1142/1143/1144/1608, CII 1334, CII*1335, CIV 1548/1550, SiII 1304/1190/1193/1260/1526,  SiII*1533, SiII*1264, SiIII1206, SiIV1393/1402, SII1250/1253/1259, OI1302, NV 1238/1242. Most lines have fval consistent with Morton 2003, except the CIV/SiIV doublets that X raised the issue here.

**Comment by jnburchett** [comment] 2017-11-19 17:20
I think Prof. Tripp should be made aware of this (will email him).  Just curious, how much did the f_osc change?

**Comment by yzhenggit** [comment] 2017-11-19 17:44
You mean the CIV and SiIV values? Morton 2003 gives fval=0.1899/0.09475 for CIV 1548/1550, and fval=0.513/0.254 for SiIV 1393/1402. I forgot what the values are quoted in linetools ... 

In terms of the difference between Morton 2003 and previous line list references, it could change quite a lot from line to line depending on which reference is used. (ps, linetools has been mostly updated to Morton 2003 with only a few lines from other more reliable sources I believe).

**Comment by tmtripp** [comment] 2017-11-19 20:24
In the cases of CIV and SiIV, the changes in the Morton 2003 atomic data compared to the earlier Morton paper (or other papers) are tiny and will only have a very small effect on line measurements.  I expect that this effect will be negligible compared to other sources of noise in most of our data.  However, if the software is erroneously grabbing the f-values from some other transition (i.e., *not* SiIV) when it is supposed to be getting the f-values for Si IV, then this will cause a problem.  This would be essentially a randomly generated f-value, which would not produce a correct measurement.

But that's the part that I find puzzling about this post: there are not any other resonance lines of any appreciable strength near the Si IV doublet that the software could have pulled.  Which species+transition was it reading instead of Si IV.

Here is my guess: this is a wrong explanation for some problem that occurred.  I will look at m own data and measurements to evaluate whether this makes sense.

**Comment by tmtripp** [comment] 2017-11-19 21:13
This thread does not make sense.  Could someone please tell me the following: what are the wavelengths and f-values that linetools was pulling previously?  And what are the values that it is pulling now?

I did a few spot checks of Si IV measurements that I made with software that uses linetools (joebvp), and the joebvp measurements look just fine compared to measurements of the same lines that I made with entirely separate programs (i.e., not using linetools at all) a long time ago.  So, I don't get it.  These tiny changes in atomic data shouldn't do much at all.

I look forward to learning more about what's going on here.  Thanks.

**Comment by jnburchett** [comment] 2017-11-20 03:14
Here are the atomic data that linetools was returning for the Si IV lines:

wrest: 1393.755 Angstrom
name: SiIV 1393
f: 0.523999989033

wrest: 1402.77 Angstrom
name: SiIV 1402
f: 0.259999990463

The new values of the oscillator strengths are in Yong's message above.  I will also note that the new wavelengths are 1393.7602 and 1402.7729.

**Comment by tmtripp** [comment] 2017-11-20 14:36
I believe that JOEBVP is doing something different than LINETOOLS...  Briefly:

(1) If the "old" wavelengths and f-values are the numbers given by Joe in the note above, then this is Much Ado About Nothing, because these tiny changes in atomic data would have a tiny effect.

(2) However, I recall that when Joe and I were testing joebvp, we came upon a similar problem, and Joe fixed the problem by allowing a somewhat larger tolerance in the delta wavelength for matching a wavelength specified in a joebvp input file with a wavelength in the linetools atomic database.  By doing this, I believe we avoided this problem with the Si IV and C IV lines.

(3) I infer that this larger tolerance was *not* used in some other application of linetools, and I infer that this must have led to a large and problematic error in Si IV and/or C IV measurements.  I suppose that linetools was pulling the atomic data for some other line entirely.  However, that other line must have been pretty far off from the correct Si IV or C IV wavelengths.

(4) Linetools should not allow this to happen.  If linetools does not find a line with a wavelength that matches within some tolerance, this should cause an exception.  At that point, linetools should stop and prevent the user from making a grave mistake.

**Comment by profxj** [comment] 2017-11-20 14:52
indeed it does.  I believe the tolerance is a few mA.
And in the case, this was too *large*.   I didn't get a hit
on Morton 2003 and instead was pulling Verner.

**Comment by jnburchett** [comment] 2017-11-20 17:23
Okay, I think we can put our concerns as regards joebvp measurements to bed here.  joebvp retrieves and uses atomic data in such ways that Todd and/or I would have noticed if the greatest concern were happening (random f_osc values because of wavelength mismatches).  

As X said, linetools does throw an exception when one tries to look up a line with a rest lambda that is outside the tolerance range of a line in the database.  For this reason, I put a 'try/except' block in the joebvp atomic data retrieval procedure to then go directly to Morton+03 and pull the closest line in the database.  The adopted rest wavelength is then that *found in Morton*, not what the user input.  So, any output from joebvp would show the wavelength associated with the rest of the data (f_osc and gamma) used in the fit.  Also, the ion names used in the GUI and in the outputs come directly from Verner, matched on rest wavelength, so mismatches would likely show up here too.

Lastly, Todd and I both have compared joebvp fits to other software, and we have seen no reason to believe that the measurements are so discrepant that egregiously erroneous atomic data should be the cause.

**Comment by tmtripp** [comment] 2017-11-20 17:31
Thanks, Joe.  So if I understand correctly, anyone using linetools will get an exception if an input line does not match the database within some tolerance.  Will joebvp stop entirely, or will it pull the closest line in the database (even if it is fairly far from the user's input line wavelength) and keep going?

I think that if an input line does not match the database within some reasonable tolerance, it is probably best for the code to stop and demand that the user use an input wavelength that matches a known line.  Otherwise, we could get wildly erroneous results and not realize it.

**Comment by jnburchett** [comment] 2017-11-20 17:47
Todd, I think wildly erroneous results that go unnoticed are very unlikely, but let's take discussion of joebvp off this thread.

**Comment by tmtripp** [comment] 2017-11-20 18:08
Joe-

   I am happy to take our discussion out of this thread.  There actually 
is a kerfuffle going down related to arXiv:1710.10703v1, and I suspect 
that this stems from this problem with linetools, although I'm not sure 
about that.  I received an email from one of the people involved, and it 
sounds like this is a pretty serious mess.  This entire paper might fall 
apart because of incorrect Si IV measurements.  One person has suggested 
that the paper should be withdrawn, but astro-ph has a messy way of 
doing that...  A paper can be marked as "withdrawn", but the preprint 
will still be available from the astro-ph archive.  Apparently, there is 
no way to *totally* erase something that has been posted there.  Kind of 
interesting... I suppose that is a good thing for historians of science, 
but it can lead to embarrassment in some situations.

   Anyway, this is why I'm a bit more stressed about this than normal (I 
realize I'm normally pretty stressed out, so this is saying something).  
As I mentioned, there is an email that was sent around to some folks, 
and it's not a great situation.

   Here is an important thing to note about this mess: the difference is 
only about 0.35 dex, so it isn't an error that jumps out at you, but it 
does make a world of difference for this particular paper.  Actually, if 
you look at one of the figures, there was evidence of a problem that the 
authors probably should have noticed...

   We are dealing with complicated data, and it is conceivable that some 
atomic data could get mixed up this way leading to insidious and 
deleterious errors, so that's why I am thinking that if an input line 
seems to whacky, it might be best to just stop the code altogether.  A 
loud and infernal alarm bell or buzzer should start ringing when this 
happens at least.

   Let me know what your thoughts are on this when you have a chance.  
Not urgent, but I think we should think about this.

Thanks,
Todd

**Comment by yzhenggit** [comment] 2017-11-20 18:33
Hi Todd, I’m actually the first author of the wrong MW CGM paper :) We realize the column density mistake almost right away after we put the paper on the arXiv (kindly pointed out by B. Savage and B. Wakker). That’s where I started checking the atomic data I’ve been using (turned out that effect was minor despite the different line list sources, it was a mistake in my own code). I’m working on it to do a replacement ASAP. 

As for withdrawn, our team did have seriously consider that option. But as you have said, withdrawn can’t eliminate the whole thing, so eventually we decided to let it sit for now and work as fast as we could for a replacement. To reduce the impact of the wrong result, I have emailed as many colleagues in this field as I could about the error immediately when the mistake was realized (sorry I didn’t reach out to you). 

Glad that this is brought up here so more people could be informed. We could discuss more about the current results I have and other things later. I’m boarding a flight back to New York, but just thought it’s better to clarify this right away. Thanks!

**Comment by tmtripp** [comment] 2017-11-20 18:39
Dear Yong,

   Thanks for the update!  I think that there is a very interesting 
question here. COS-Halos detected very high OVI column densities at 
large impact parameters, and if the Milky Way had a similar large halo 
of highly ionized gas, it should be possible to detect that halo toward 
extragalactic sight lines.  My suspicion is that the Milky Way is 
fundamentally different from the typical galaxies that were studied in 
the COS-Halos survey.  This is an important question, and I look forward 
to learning more from ongoing studies like your project.

Best regards,
Todd

**Comment by yzhenggit** [comment] 2017-11-21 03:23
Thanks Todd! Yes, that's what we were getting excited at -- to see whether the MW's halo is as massive as other CGM observed at higher z. I'll keep you posted as I make new progress. 

Cheers,
-Yong

**Closed** 2017-11-27 14:02 UTC
